targets:
  $default:
    builders:
      # Builder is imported directly from src/build/swagger_builder.dart
      # to avoid loading dart:mirrors in normal usage
      dart_swagger_to_models|swaggerBuilder:
        enabled: true
        generate_for:
          - swagger/**
          - openapi/**
          - api/**
