targets:
  $default:
    builders:
      # Builder импортируется напрямую из src/build/swagger_builder.dart
      # чтобы избежать загрузки dart:mirrors при обычном использовании
      dart_swagger_to_models|swaggerBuilder:
        enabled: true
        generate_for:
          - swagger/**
          - openapi/**
          - api/**
